#!/bin/bash
#
# PaperOrchestra setup — configures skill discovery for supported AI agents.
#
# Usage: bash setup.sh
#
# What it does:
#   1. Creates .env from .env.example (if not present) and optionally prompts for
#      integration settings.
#   2. Symlinks skills/* into project-local and global skill directories for
#      common hosts.
#   3. Writes ~/.paperorchestra/config with the resolved optional integration
#      values so wrapper scripts can discover the repo.
#   4. Prints a concise summary and points to the host integration docs.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SKILLS_DIR="$SCRIPT_DIR/skills"
ENV_FILE="$SCRIPT_DIR/.env"
ENV_EXAMPLE_FILE="$SCRIPT_DIR/.env.example"
GLOBAL_CONFIG_DIR="$HOME/.paperorchestra"
GLOBAL_CONFIG="$GLOBAL_CONFIG_DIR/config"

if [ ! -d "$SKILLS_DIR" ]; then
  echo "ERROR: expected skills/ next to setup.sh" >&2
  exit 1
fi

if ! command -v python3 >/dev/null 2>&1; then
  echo "ERROR: setup.sh requires python3 to update .env and write ~/.paperorchestra/config" >&2
  exit 1
fi

# Symlink every skill in SKILLS_DIR into TARGET_DIR.
# Skips real directories to avoid data loss; updates stale symlinks.
install_skills() {
  local target_dir="$1"
  local label="$2"
  mkdir -p "$target_dir"
  for skill in "$SKILLS_DIR"/*/; do
    local skill_name link_path
    skill_name="$(basename "$skill")"
    link_path="$target_dir/$skill_name"
    if [ -L "$link_path" ]; then
      rm "$link_path"
    elif [ -e "$link_path" ]; then
      echo "⚠️   $link_path exists and is not a symlink, skipping"
      continue
    fi
    ln -s "${skill%/}" "$link_path"
  done
  echo "✅  Installed skills → $label"
}

ensure_env_file() {
  if [ ! -f "$ENV_FILE" ]; then
    if [ -f "$ENV_EXAMPLE_FILE" ]; then
      cp "$ENV_EXAMPLE_FILE" "$ENV_FILE"
      echo "✅  Created .env from .env.example"
    else
      touch "$ENV_FILE"
      echo "✅  Created empty .env"
    fi
  else
    echo "✅  .env already exists"
  fi
}

read_env_val() {
  python3 - "$ENV_FILE" "$1" <<'PY'
import pathlib, sys
path = pathlib.Path(sys.argv[1])
key = sys.argv[2]
if not path.exists():
    print("")
    raise SystemExit(0)
for line in path.read_text().splitlines():
    if line.startswith(f"{key}="):
        print(line.split("=", 1)[1])
        raise SystemExit(0)
print("")
PY
}

write_env_val() {
  python3 - "$ENV_FILE" "$1" "$2" <<'PY'
import pathlib, sys
path = pathlib.Path(sys.argv[1])
key = sys.argv[2]
value = sys.argv[3]
lines = path.read_text().splitlines() if path.exists() else []
out = []
replaced = False
for line in lines:
    if line.startswith(f"{key}="):
        out.append(f"{key}={value}")
        replaced = True
    else:
        out.append(line)
if not replaced:
    out.append(f"{key}={value}")
path.write_text("\n".join(out).rstrip("\n") + "\n")
PY
}

prompt_env_var() {
  local var_name="$1"
  local prompt_text="$2"
  local current_val
  current_val="$(read_env_val "$var_name")"

  if [ -n "$current_val" ] && [ "$current_val" != "your_key_here" ]; then
    echo "✅  $var_name already set"
    return
  fi

  echo ""
  read -r -p "  $prompt_text (leave blank to skip): " input_val || input_val=""
  if [ -n "${input_val:-}" ]; then
    write_env_val "$var_name" "$input_val"
    echo "  → $var_name saved to .env"
  else
    echo "  → Skipped $var_name"
  fi
}

write_global_config() {
  mkdir -p "$GLOBAL_CONFIG_DIR"
  cat > "$GLOBAL_CONFIG" <<EOF
# Auto-generated by setup.sh
SEMANTIC_SCHOLAR_API_KEY=$(read_env_val SEMANTIC_SCHOLAR_API_KEY)
EXA_API_KEY=$(read_env_val EXA_API_KEY)
PAPERBANANA_PATH=$(read_env_val PAPERBANANA_PATH)
PAPERORCHESTRA_REPO=$SCRIPT_DIR
EOF
  echo ""
  echo "✅  Global config written to ~/.paperorchestra/config"
}

print_summary() {
  local skill_count
  skill_count=$(find "$SKILLS_DIR" -mindepth 1 -maxdepth 1 -type d | wc -l | tr -d ' ')

  echo ""
  echo "───────────────────────────────────────────────────"
  echo " Setup complete!"
  echo ""
  echo " Skills installed: $skill_count"
  echo " Agents ready: Claude Code, Cursor, Windsurf, Antigravity/Gemini, Codex, OpenClaw"
  echo ""
  echo " Optional integrations (.env + ~/.paperorchestra/config):"
  echo "   SEMANTIC_SCHOLAR_API_KEY  → higher Semantic Scholar throughput"
  echo "   EXA_API_KEY               → Exa candidate discovery backend"
  echo "   PAPERBANANA_PATH          → local PaperBanana checkout for diagrams"
  echo ""
  echo " Next steps:"
  echo "   1. Review docs/coding-agent-integration.md for your host"
  echo "   2. Scaffold a workspace with skills/paper-orchestra/scripts/init_workspace.py"
  echo "   3. Ask your agent to run the paper-orchestra skill on that workspace"
  echo "───────────────────────────────────────────────────"
  echo ""
}

echo ""
echo "╔══════════════════════════════════════════════════╗"
echo "║         PaperOrchestra — Agent Setup             ║"
echo "╚══════════════════════════════════════════════════╝"
echo ""

ensure_env_file
prompt_env_var "SEMANTIC_SCHOLAR_API_KEY" "Semantic Scholar API key (optional)"
prompt_env_var "EXA_API_KEY" "Exa API key (optional)"
prompt_env_var "PAPERBANANA_PATH" "Path to a local PaperBanana checkout (optional)"
write_global_config

AGENT_DIRS=(
  ".claude/skills"
  ".cursor/skills"
  ".windsurf/skills"
  ".agents/skills"
)

for agent_dir in "${AGENT_DIRS[@]}"; do
  install_skills "$SCRIPT_DIR/$agent_dir" "$agent_dir/"
done

install_skills "$HOME/.claude/skills" "~/.claude/skills/ (Claude Code, global)"
install_skills "$HOME/.agents/skills" "~/.agents/skills/ (OpenClaw + generic)"
install_skills "$HOME/.codex/skills" "~/.codex/skills/ (Codex)"
install_skills "$HOME/.gemini/antigravity/skills" "~/.gemini/antigravity/skills/ (Gemini)"

print_summary
